### ISSUE TITLE
强烈建议给组件增加一个是否必输的选项

### ISSUE THREAD

**Issue by johnniehs** [form-render/schema-generator#10]
如题，强烈建议给组件属性增加一个 是否必输 的选项。这个太重要了，没有这个生成出来表单项，无法校验用户的输入

**Comment by FateRiddle** [comment]
好的。这个会加上。这周内。

**Comment by F-loat** [comment]
已支持 73c5b8fbb8f205c2e6a74445a35e60f2497db918
