### ISSUE TITLE
希望此框架更加定制化

### ISSUE THREAD

**Issue by crimson968** [form-render/schema-generator#15]
1.希望左侧的控件配置项可以选择自定义配置或默认配置，目前自定义配置只支持模板模块，模块名同时可以自主配置，例如基础组件自定义名为：普通组件等。

2.希望右侧的属性配置部分可以通过自定义插件的形式注入，例如输入框的组件配置最下方可以自定义追加：是否必填项等，按照官方约定的格式进行插件开发即可。

**Comment by FateRiddle** [comment]
收到，在这周会放开。

**Comment by fatesq** [comment]
> 收到，在这周会放开。

请问放开了吗

**Comment by flybrotheryao** [comment]
同问，开放了吗

**Comment by rankyangel2014** [comment]
请问 如何配置组件是否为必填项

**Comment by tw93** [comment]
@rankyangel2014 @fatesq  可见这里 https://x-render.gitee.io/schema-generator/demo#%E5%B7%A6%E5%8F%B3%E4%BE%A7%E6%A0%8F%E9%85%8D%E7%BD%AE--%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6
