### ISSUE TITLE
VSCode 插件

### ISSUE THREAD

**Issue by F-loat** [form-render/schema-generator#16]
开发了一个 [vscode 插件](https://github.com/F-loat/vscode-plugin-fr-schema.git) 来实现在编辑器内直接修改 json schema，希望可以开放以下配置，增强插件能力

* 事件 onSchemaChange

* 属性 defaultButtons

  通过形如 `defaultButtons={['preview', 'clear']}` 的配置来具体控制头部按钮的渲染与否

* 属性 leftBlocks

  通过形如 `leftBlocks={['basic', 'complex', 'layout']}` 的配置来具体控制左侧区块的渲染与否

* 支持 antd 的主题定制

  引用 `antd/dist/antd.less` 而非 [`antd/dist/antd.css`](https://github.com/form-render/schema-generator/blob/dev/src/Main.js#L9)  ([官方文档](https://ant.design/docs/react/customize-theme-cn#%E6%B2%A1%E6%9C%89%E7%94%9F%E6%95%88%EF%BC%9F))

![image](https://user-images.githubusercontent.com/16759376/93329934-90490c80-f850-11ea-83cd-4bda6cb09fd7.png)

**Comment by tw93** [comment]
很厉害的样子

**Comment by FateRiddle** [comment]
1. defaultButtons 这个，现在可以用 extraButtons 来配置了。https://x-render.gitee.io/schema-generator/config#extrabuttons
2. 事件 onSchemaChange 还是暂时不放出了，内部的schema有一些多余的信息，开发要用，用户没用。直接用 getValue 和 setValue 好了。
其他的部分这周内都上去。
