### ISSUE TITLE
尝试自定义配置后构建失败

### ISSUE THREAD

**Issue by jszyy** [form-render/schema-generator#17]
查找引用指向dist目录下。根据文件目录查找到左侧菜单栏配置在src/Left/elementList.js中。尝试修改 elements 声明，增加 upload 组件后运行 npm run build 后报错：
![image](https://user-images.githubusercontent.com/48779641/93302760-118ea800-f82d-11ea-9d7f-0ea9446a5385.png)
或许可以通过创建模板的方式达到此目的，但为了更好的使用体验，有没有其他方式来支持更多已有或自定义组件？

**Comment by FateRiddle** [comment]
在这周会放开。

**Comment by Harvey-ZTC** [comment]
> 在这周会放开。

请问一下这个大概什么时候能放开呢？好几个周了=-=

**Comment by flybrotheryao** [comment]
同问，这个功能，求解

**Comment by ChenYCL** [comment]
同求,想自行拓展Left ,Right 的tab部分,目前看源码只能强行改了

**Comment by tw93** [comment]
@ChenYCL @jszyy @flybrotheryao 
可见这里
https://x-render.gitee.io/schema-generator/demo#%E5%B7%A6%E5%8F%B3%E4%BE%A7%E6%A0%8F%E9%85%8D%E7%BD%AE--%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6
