### ISSUE TITLE
升级V0.5.2导致ID值为#号

### ISSUE THREAD

**Issue by kfypmqqw** [form-render/schema-generator#18]
导入默认的schema
`{
  "schema": {
    "type": "object",
    "properties": {
      "inputName": {
        "title": "简单输入框",
        "type": "string"
      }
    }
  },
  "displayType": "row",
  "showDescIcon": true,
  "labelWidth": 120
}`
在组件配置的ID值为“#”号

原因是getDataById获取的data为null。导致flatten里面的data数据都为null
// TODO: 没有考虑list的情况
export const dataToFlatten = (flatten, data) => {
  if (!flatten || !data) return {};
  Object.entries(flatten).forEach(([id, item]) => {
    const branchData = getDataById(data, id);
    flatten[id].data = branchData;
  });
  return flatten;
};

**Comment by F-loat** [comment]
A simple workaround https://github.com/F-loat/schema-generator/commit/810f06fc7b8295603ab935123c5f6375e7e532d4

**Comment by FateRiddle** [comment]
已经fix了。新版本。

**Comment by mark5566** [comment]
> 已经fix了。新版本。

直接下载源码运行，发现还是有类似的问题


点击左侧组件

中间预览界面显示了正确的ID
但是，该组件的“组件配置”（右边）的id输入框显示的“#”

每次修改组件的任意配置，都会自动删除该组件

**Comment by mark5566** [comment]
> > 已经fix了。新版本。
> 
> 直接下载源码运行，发现还是有类似的问题
> 
> 点击左侧组件
> 
> 中间预览界面显示了正确的ID
> 但是，该组件的“组件配置”（右边）的id输入框显示的“#”
> 
> 每次修改组件的任意配置，都会自动删除该组件

版本号：0.5.4

**Comment by mark5566** [comment]
![Uploading image.png…]()

**Comment by mark5566** [comment]
![image](https://user-images.githubusercontent.com/11515695/95670030-44705580-0bb9-11eb-9ed8-59bbeec4c831.png)

**Comment by mark5566** [comment]
@FateRiddle
