### ISSUE TITLE
可视化编辑schema的全局属性配置后，注入到schema内部

### ISSUE THREAD

**Issue by karzanOnline** [form-render/schema-generator#29]
### 期望的新功能

schema可视化编辑界面的全局属性，直接注入到每个属性的内部。

#### 业务使用问题

1. 全局的配置，只能对全局生效。业务使用中对上面的区块是1排1的，下面的区块是1排3的，这种需求目前是支持不了的，限制了业务的使用场景。

#### 开发者使用问题

1. Schema 存储时需要剥离全局的 ui 渲染属性。当开发者需要把编辑好的 Schema 数据传给服务端时，需要强行拆解内部的 Schema 把里面纯粹的 Schema 剥离出来。

**Comment by F-loat** [comment]
1排1、1排3 的效果可以通过元素宽度实现，标签宽度也可以直接在子元素上配置，其他需求建议自行封装 schema 转换函数，可通过 [transformer](https://x-render.gitee.io/schema-generator/config#transformer) 属性配置
