### ISSUE TITLE
问一下我想直接引入源码是哪一部分啊，我引用包的话你们引用的antd版本和我的不一样会引起样式问题，应该如何解决啊

### ISSUE THREAD

**Issue by haulong** [form-render/schema-generator#3]

**Comment by FateRiddle** [comment]
问题可能出在样式入侵。已经在新版解决。

考虑到使用者不一定是antd的用户，所以这个包是不会默认依赖用户的antd版本的。所以目前确实有引入会多一份antd的问题，这里有没有好的想法可以交流哦。加入form-render的钉钉群也行哈
