### ISSUE TITLE
在右边属性设置里可以切换组件类型

### ISSUE THREAD

**Issue by zhousufa** [form-render/schema-generator#31]
schema的defaultValue是通过mock数据生成的，我用这个schema-generator是用来完善title和一些属性设置。
一个string字段通过mock生成schema的时候默认是input，但是根据具体业务他可能是哥图片上传或者富文本，textarea等，所以希望增加在右侧切换的功能

**Comment by kfypmqqw** [comment]
右边去做转换可能比较麻烦，因为右边的数据改变是用数据改变监听的，使用每个元素的工具栏会方便一点，可以参考一下这个修改shttps://github.com/kfypmqqw/schema-generator/commit/6253888c24e7e3433daf236a36015a4330464c48

**Comment by zhousufa** [comment]
> 右边去做转换可能比较麻烦，因为右边的数据改变是用数据改变监听的，使用每个元素的工具栏会方便一点，可以参考一下这个修改shttps://github.com/kfypmqqw/schema-generator/commit/6253888c24e7e3433daf236a36015a4330464c48

我先看看
