### ISSUE TITLE
关于必选项的问题

### ISSUE THREAD

**Issue by sagittarius-rev** [form-render/schema-generator#33]
文档并没有提及必选项的设置。但查阅了源码，发现实际上已经包含对必选项（ required ）的处理。

但具体使用方式十分别扭。源码中判断了 required 的长度，不知道意图是作为字符串来对待，还是作为数组对待。

使用以下配置可以增加必选项设置：

```javascipt
required: {
  title: '是否必选',
  type: 'string',
  enum: ['required', ''],
  enumNames: ['是', '否'],
},
```

如果导入默认的公用设置 defaultCommonSettings ，加入对于必选项的设置并使用，就可以实现所有输入项都出现“必选项”的选择。

**但目前仍然存在以下问题：**

1. 源码为什么要判断 required 的长度？正常这个项目应当是作为 boolean 来处理的，而不是像上面代码那样做成下拉选择项。
1. 对于复杂结构（对象、列表、模板），只需要在子项目上选择“是否必选”，不需要在整体结构上做选择。这一点以目前的实现方式，难以简便解决。

**Comment by sagittarius-rev** [comment]
使用 `"ui:widget": "radio"` 可以让这个选项变为 radio ，但仍然达不到预期的效果，即呈现为 checkbox 。

**Comment by wlx200510** [comment]
发现这么配置后并没有与form-render 联动，两者required声明方式不同

**Comment by F-loat** [comment]
已支持 73c5b8fbb8f205c2e6a74445a35e60f2497db918
