### ISSUE TITLE
templates 参数无效

### ISSUE THREAD

**Issue by sagittarius-rev** [form-render/schema-generator#34]
`FRWrapper` 组件会接收 `templates` 参数，并将其转为 `saveList` 属性传递给 `Left` 组件。

而 `Left` 组件接收了 `saveList` 参数（以及关联的设置方法 `setSaveList` ）后，根本没有进行使用，导致 `templates` 参数设置之后完全无效。

希望修正此问题。

**Comment by wjjhhh** [comment]
+1

**Comment by F-loat** [comment]
templates 属性已经废弃，可以通过 [settings](https://x-render.gitee.io/schema-generator/config#settings--commonsettings--globalsettings) 定制各面板
