### ISSUE TITLE
cra创建的ts版本,安装后找不到接口定义,后期会有@types么

### ISSUE THREAD

**Issue by ChenYCL** [form-render/schema-generator#36]
![image](https://user-images.githubusercontent.com/25706676/102298358-f21e2d00-3f8b-11eb-85f8-348ca5bc731e.png)

**Comment by rankyangel2014** [comment]
可以使用 微软的dts-gen 自动生成 *d.ts 文件

**Comment by ChenYCL** [comment]
> 可以使用 微软的dts-gen 自动生成 *d.ts 文件

直接报错了 无法修饰less等

**Comment by rankyangel2014** [comment]
`
declare module 'fr-generator/dist' {
    export interface GeneratorProps {
        defaultValue?: object;
        templates?: array;
        transformer?: object;
        extraButtons?: array;
        settings?: array;
        commonSettings?: object;
        globalSettings?: object;
        widgets?: object;
        getValue?: () => any;
        setValue?: (schema: any) => void;
        copyValue?: () => void;

    }
    class Generator extends React.Component<GeneratorProps> { }
    export default Generator;

}`

**Comment by rankyangel2014** [comment]
![image](https://user-images.githubusercontent.com/8031724/104165788-d3993d80-5434-11eb-91c2-b3de12ea3cf2.png)


`

declare module 'fr-generator/dist' {
    export interface GeneratorProps {
        defaultValue?: object;
        templates?: array;
        transformer?: object;
        extraButtons?: array;
        settings?: array;
        commonSettings?: object;
        globalSettings?: object;
        widgets?: object;
        getValue?: () => any;
        setValue?: (schema: any) => void;
        copyValue?: () => void;

    }
    class Generator extends React.Component<GeneratorProps> { }
    export default Generator;

}
`

**Comment by ChenYCL** [comment]
嗯嗯 好的谢谢,目前只能先这样
