### ISSUE TITLE
将Form Render嵌套在schema-generator中，Form Render的校验不起作用了

### ISSUE THREAD

**Issue by jxsd-muyezi** [form-render/schema-generator#39]
![image](https://user-images.githubusercontent.com/40133776/109928512-7d43cf00-7d00-11eb-841b-5e40636c9015.png)

**Comment by jxsd-muyezi** [comment]
如何实现配置项的校验，必填校验，校验验证规则等

**Comment by F-loat** [comment]
form-render1.0 发布后，schema 编辑器会完善相关支持
