### ISSUE TITLE
onSchemaChange回调问题

### ISSUE THREAD

**Issue by NerdC** [form-render/schema-generator#47]
https://github.com/form-render/schema-generator/issues/45#issue-850911648
 根据手动创建ref 解决了报错的问题，但是在onSchemaChange回调的数据是不是最新的，是返回的上一步的数据，望下版一并修复。

**Comment by F-loat** [comment]
Fixed https://github.com/alibaba/form-render/commit/1cf45d7737d2520254b9cd912169256880ab464a
