### ISSUE TITLE
编辑器加入html类型的组件(type: "html")时报错

### ISSUE THREAD

**Issue by guohaolong** [form-render/schema-generator#48]
FR 可视化schema编辑器加入html类型的组件时，报错。
    "form-render": "0.10.0",
    "fr-generator": "1.1.0",

代码地址：https://codesandbox.io/s/form-render-forked-8gj55?file=/src/index.js
拖放“HTML元素”组件时报错：input is a void element tag and must neither have `children` nor use `dangerouslySetInnerHTML`.

**Comment by F-loat** [comment]
暂不支持，适配 fr1.0 后会对齐这部分能力，后面更新在 [x-render](https://github.com/alibaba/x-render) 仓库
