### ISSUE TITLE
基础组件丰富

### ISSUE THREAD

**Issue by Monseul** [form-render/schema-generator#5]
你好，我在开发中遇到一些问题：
1、目前schema-generator左侧基础组件中没有支持上传组件
2、select组件引入api的需求，需要通过api获取下拉列表
3、组件配置中缺少必填功能
4、组件配置中期望通过JS表达式隐藏与禁用组件

**Comment by rankyangel2014** [comment]
5，希望右侧的 【组件配置】和 【表单配置】可以动态显示或隐藏

**Comment by F-loat** [comment]
1，2 ，4 可以通过[自定义组件](https://x-render.gitee.io/schema-generator/demo#%E5%B7%A6%E5%8F%B3%E4%BE%A7%E6%A0%8F%E9%85%8D%E7%BD%AE--%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6)来实现

3 已支持 73c5b8fbb8f205c2e6a74445a35e60f2497db918

5，6 暂不计划支持，特殊需求可通过 css 进行控制
