### ISSUE TITLE
 自定义组件

### ISSUE THREAD

**Issue by lyl-moon** [form-render/schema-generator#7]
现在里面都是基础组件，跟有些需求的组件样式及组件类型不太相符，请问后续会考虑让开发者添加自定义组件吗

**Comment by tw93** [comment]
已经支持，可见 https://x-render.gitee.io/schema-generator/demo#%E5%B7%A6%E5%8F%B3%E4%BE%A7%E6%A0%8F%E9%85%8D%E7%BD%AE--%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6
