### ISSUE TITLE
全局样式污染?

### ISSUE THREAD

**Issue by pkaq** [form-render/schema-generator#8]
在pro的v5版本里 只要有组件 
```
import Generator from 'fr-generator';
```
就会出现如下惨状
![3333](https://user-images.githubusercontent.com/4537450/90086520-30d97780-dd4d-11ea-9517-feffdcdc769e.png)

**Comment by FateRiddle** [comment]
0.5.1 fixed

**Comment by pkaq** [comment]
> 0.5.1 fixed

似乎更新并且清除缓存访问后并没有什么变化

**Comment by pkaq** [comment]
@FateRiddle   ??? 0.5.1 在 v5 下依旧有问题呀
