### ISSUE TITLE
引入后会栈溢出

### ISSUE THREAD

**Issue by Meikongggg** [form-render/schema-generator#9]
![1597816099(1)](https://user-images.githubusercontent.com/32662465/90597030-d9427c80-e222-11ea-8114-c661ca5b168c.jpg)
![1597816121(1)](https://user-images.githubusercontent.com/32662465/90597033-db0c4000-e222-11ea-9dfb-ece8b3a10720.jpg)

**Comment by FateRiddle** [comment]
试试看使用官方demo的方式引入。https://x-render.gitee.io/schema-generator/demo
最近也升级过了，再尝试一下看看？抱歉体验差了。还有问题就继续打开这个issue撒。
